### ISSUE TITLE
SSDT for EC not working.

### ISSUE THREAD

**Issue by Mateo1234454545** [corpnewt/SSDTTime#1]
I made a ssdt-ec with your tool but my laptop doesn't boot.
I have to rename ECDV to EC to boot.
[SSDT-EC.aml.zip](https://github.com/corpnewt/SSDTTime/files/3665881/SSDT-EC.aml.zip)

Seems that ECDV device is mandatory.

**Comment by corpnewt** [comment]
For a laptop, you don't want to fake the EC device anyway, so that makes sense.  You'll likely want to rename, then ensure that battery stats are patched - but that's beyond the current scope of this script.

-CorpNewt
