### ISSUE TITLE
Option 4 is missing

### ISSUE THREAD

**Issue by codecowboy** [corpnewt/SSDTTime#24]
On MacOS Catalina 10.15.2, If I run` ./SSDTTime.command`, Option 4 is missing. If I select Option 3, I am asked to drag the DSDT.aml onto the terminal, this has no effect. The DSDT.aml file is located in a folder on the Desktop.

I was able to do this under Linux which is how I dumped the DSDT originally.

I'm following the guide here - https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html

![Screenshot 2020-06-01 at 09 16 57](https://user-images.githubusercontent.com/178432/83390039-0bdd9580-a3e9-11ea-8e5b-a1d41664c99e.png)

**Comment by corpnewt** [comment]
This is by design. The DSDT you would get within macOS will already have ACPI renames and patches applied - and as such will likely be inaccurate to use as a source for the SSDTs generated.

-CorpNewt
