### ISSUE TITLE
[macOS Catalina 10.15.6] Can't download iasl

### ISSUE THREAD

**Issue by dreamwhite** [corpnewt/SSDTTime#31]
Hi @corpnewt and many thanks for your new update (AWAC and PMC are really useful). 
I've updated SSDTTime by recloning your repo and when I launch SSDTTime.command an error is displayed:

`Downloading iasl.zip`
` - Extracting`
`An error occurred :(`
` - [Errno 2] No such file or directory: '/var/folders/j_/5cg1hs7j2rl4srlr9c5pjm4h0000gn/T/tmpnioflwtm/tmpush7dk76/iasl.zip'`
`Something went wrong :( - Aborting!`
` - Could not locate or download iasl!`

I've fixed by manually copying my iasl to Scripts folder. 
What can you do to fix this? Can't you attach iasl latest version to the Scripts folder? 
Thanks

**Comment by stellqrr** [comment]
You need to download the UNIX source code packages from [here](https://www.acpica.org/downloads) and then copy the iasl from bin and paste it in Scripts folder in SSDTTime directory

**Comment by loadream** [comment]
https://www.acpica.org/downloads/binary-tools  uzip all .exe file to Scripts
