### ISSUE TITLE
Error: Could not locate or download iasl!

### ISSUE THREAD

**Issue by Flaam** [corpnewt/SSDTTime#38]
dont know how to fix it lol

**Comment by AnsonX10** [comment]
I can confirm but this is a Linux only issue. http://amdosx.kellynet.nl/iasl.zip cannot be downloaded because kellynet.nl is down at the moment.

**Comment by AnsonX10** [comment]
I've tested and the iasl binary from the acpica package (in the Arch repos) works just fine. The script could probably just check if there is an iasl binary already on the system, and use that instead of downloading it.

**Comment by Flaam** [comment]
@AnsonX10 i downloaded iasl.zip but where should i put it

**Comment by n-cal** [comment]
This worked for me:
`sudo apt-get install iasl`
`cp /usr/bin/iasl path/to/SSDTTime-master/Scripts/iasl`

**Comment by AnsonX10** [comment]
Yes, putting (or even just linking) iasl inside the Scripts folder will work.

**Comment by Flaam** [comment]
This fixed the issue, thanks, closing.

> This worked for me:
> `sudo apt-get install iasl`
> `cp /usr/bin/iasl path/to/SSDTTime-master/Scripts/iasl`
