### ISSUE TITLE
SSDT-PLUG generation doesn't support _SB_.PR00

### ISSUE THREAD

**Issue by tanyakarn** [corpnewt/SSDTTime#4]
The SSDT-PLUG generated by the script seems to only look for CPU0 vs PR00 but in some cases, the scope that PR00 belongs to is \_SB, not \_PR.

**Comment by corpnewt** [comment]
If you have a copy of a DSDT that has the CPU0/PR00 at _SB instead of _PR, could you send it here and I'll see if I can come up with a reasonable way to detect the scope correctly?

-CorpNewt

**Comment by tanyakarn** [comment]
[DSDT.aml.zip](https://github.com/corpnewt/SSDTTime/files/3752244/DSDT.aml.zip)

**Comment by corpnewt** [comment]
Should be fixed in [this commit](https://github.com/corpnewt/SSDTTime/commit/cc28d836e14b4d8e05e60d29a56db8178e87a8f4).  Mind testing and letting me know if that works for you?

-CorpNewt

**Comment by tanyakarn** [comment]
It works now, thanks!

**Comment by corpnewt** [comment]
Np - thanks for letting me know.

-CorpNewt

**Comment by d4vinder** [comment]
Hi, Any chance you could take a look at my DSDT. The script seems to abort with the above-mentioned error. Many thanks.
[DSDT.aml.zip](https://github.com/corpnewt/SSDTTime/files/4842464/DSDT.aml.zip)
