### ISSUE TITLE
SSDTTime.bat not running

### ISSUE THREAD

**Issue by Luke-Wei** [corpnewt/SSDTTime#45]
![error](https://user-images.githubusercontent.com/46917749/110239122-54317180-7f80-11eb-9d73-eb0ea26dd556.jpg)
why this error occur?

**Comment by Jain-cc** [comment]
I also encountered the same problem.

**Comment by tiziodcaio** [comment]
If you delete it and re-download it?

**Comment by Luke-Wei** [comment]
The network was blocked ...
we guys live in China need VPN
