### ISSUE TITLE
[Feature Request] Add HyperV auto stuff

### ISSUE THREAD

**Issue by MysticalOS** [corpnewt/SSDTTime#47]
Ref https://github.com/acidanthera/OpenCorePkg/commit/798cc4b7ae377b17543c00fc2cd9e688b7f52709

**Comment by corpnewt** [comment]
Hey there - the sample SSDTs referenced are already universal, and shouldn't require any customization per system, so there's not really a need for SSDTTime support.

-CorpNewt
