### ISSUE TITLE
ModuleNotFoundError: No module named 'Scripts'

### ISSUE THREAD

**Issue by Unixware** [corpnewt/SSDTTime#49]
No matter I did install the "Scripts" module - even as su, still complaints that can't find them, unless I am missing something there, is it only python2 compatible?

```
Traceback (most recent call last):
  File "/home/chris/Desktop/mac/./SSDTTime.py", line 1, in <module>
    from Scripts import *
ModuleNotFoundError: No module named 'Scripts'
```

system info : Debian Sid / Python 3.9.7

thanks in advance

**Comment by Unixware** [comment]
sorry!! issue was due to corrupted py!

**Comment by jiangpaipai314** [comment]
i tried py3 but it doesnt work, so i switched to py2 and it works!!!!!
