### ISSUE TITLE
Problem with SSDTTime.bat

### ISSUE THREAD

**Issue by Sandro642** [corpnewt/SSDTTime#58]
Hello i have a problem with SSDTTime the launcher not functionnal.

Help me
![image](https://user-images.githubusercontent.com/84270313/209857227-dabdd3f6-a218-40f6-9cee-4240cece208a.png)

**Comment by corpnewt** [comment]
Hey there, what version of python are you running?

**Comment by Sandro642** [comment]
Python --version : 2.7.2 it's good ?

**Comment by corpnewt** [comment]
That's terribly old. If you can, try with a newer version and see if that fixes it?

**Comment by Sandro642** [comment]
okay i will try

**Comment by Sandro642** [comment]
Thank you is good .
