### ISSUE TITLE
An error occurred , could not locate or download iasl

### ISSUE THREAD

**Issue by nahxog** [corpnewt/SSDTTime#59]
Today im trying use SSDTtime but i got this error, how to fix it please? thanks
![image](https://user-images.githubusercontent.com/92006941/229295929-05b19c68-dc26-45c2-9b0a-3450af974523.png)

**Comment by HenilJain** [comment]
Download the Zip from https://acpica.org/downloads/binary-tools
Extract it and copy the ' iasl ' application to your ' SSDTTime-master\Scripts ' 
Rerun the application and it solves the issue

**Comment by nahxog** [comment]
@HenilJain Thank you so much, i solved the problem.
