### ISSUE TITLE
Windows10: No  Dump DSDT option 

### ISSUE THREAD

**Issue by abdurrahmanseyidoglu** [corpnewt/SSDTTime#63]
There is no Dump DSDT option is it renamed?

![image](https://github.com/corpnewt/SSDTTime/assets/40239163/f09d7acd-7e19-4690-8014-102d19c41531)

**Comment by corpnewt** [comment]
Yes - it is `P. Dump the current system's ACPI tables` - SSDTTime now dumps all available tables instead of *just* the DSDT.  For some of the functions, it will also search multiple tables, which can lessen the burden on the user to find which table contains relevant info.

-CorpNewt
