### ISSUE TITLE
An error occurred: 'SSDT' object has no attribute 'iasl_legacy'

### ISSUE THREAD

**Issue by theoparis** [corpnewt/SSDTTime#65]
Seems to happen with python 3.13 on windows.

**Comment by arka003** [comment]
Same problem for macOS with python3.12

**Comment by corpnewt** [comment]
Should be fixed as of [this commit](https://github.com/corpnewt/SSDTTime/commit/68b9abb38f147790c14bbd8a79563cfb56522405).  Let me know if you run into more problems 👍 

-CorpNewt
