### ISSUE TITLE
Merge script thingy not working on macOS

### ISSUE THREAD

**Issue by QuifixOfficial** [corpnewt/SSDTTime#67]
When clicking 1 it just switches the "current config.plist" line. This is using macOS 14.5 on an m2 pro. The .command file was used.

Please refer to the video sent in the Hackintosh server: https://discord.com/channels/186648463541272576/251043252046659586/1260710527458480230

**Comment by corpnewt** [comment]
PatchMerge looks within the `Results` folder next to it for the `patches_OC.plist` - you do not drag and drop that plist onto the script.

-CorpNewt
